name: Deploy to PyPI

on:
  workflow_call:
    inputs:
      platform:
        required: false
        type: string
        default: 'ubuntu-latest'
        description: 'The platform to run the tests on'
      python-version:
        required: false
        type: string
        default: '3.x'
        description: 'The python version to use'
      generate_release_notes:
        required: false
        type: boolean
        default: true
        description: 'Whether to generate release notes'
    secrets:
      twine_api_key:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ${{ inputs.platform }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}

      - name: Build
        run: |
          git tag
          pip install -U pip
          pip install -U build twine
          python -m build
          twine check dist/*
          ls -lh dist

      - name: Upload
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.twine_api_key }}

      - name: Generate Github Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: ${{ inputs.generate_release_notes }}
